name: Foo
on:
  pull_request:
  pull_request_target:
  workflow_dispatch:
  push:
jobs:
  foo:
    runs-on: ubuntu-latest
    if: >-
      ( github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.fork == 'true' ) ||
      ( github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == 'false' ) ||
      ( github.event_name == 'push' || github.event_name == 'workflow_dispatch' )
    steps:
      - name: Checkout the merged commit from PR and base branch
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v2
        with:
          # repository: ${{ github.event.pull_request.head.repo.full_name }}
          # ref: ${{ github.event.pull_request.head.ref }}
          # ref: refs/pull/${{ github.event.pull_request.number }}/merge
          ref: refs/pull/${{ github.event.pull_request.number }}/head
      - name: Checkout the head commit of the branch
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: actions/checkout@v2

      - name: debug info
        run: |
          echo event name: ${{ github.event_name }}
          echo repo full name: ${{ github.event.pull_request.head.repo.full_name }}
          echo repository: ${{ github.repository }}
          echo fork: ${{ github.event.pull_request.head.repo.fork }}
          echo repo id: ${{ github.event.pull_request.head.repo.id }}
          echo base repo id: ${{ github.event.pull_request.base.repo.id }}
          printenv

      - name: foochanged
        run: echo "do stuff involving [${{ secrets.Foo }}]"
