name: Foo
on:
  pull_request:
  pull_request_target:
  workflow_dispatch:
  push:
jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the merged commit from PR and base branch
        uses: actions/checkout@v2
        with:
          # repository: ${{ github.event.pull_request.head.repo.full_name }}
          # ref: ${{ github.event.pull_request.head.ref }}
          # ref: refs/pull/${{ github.event.pull_request.number }}/merge
          ref: refs/pull/${{ github.event.pull_request.number }}/head

      - name: foo
        run: echo "do stuff involving ${{ secrets.Foo }}"